name: voice_ai_assistant
description: A voice-controlled AI assistant using Flutter and Hugging Face API.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  speech_to_text: ^6.6.0
  http: ^1.2.0
  flutter_chat_ui: ^1.6.6
  flutter_chat_types: ^3.6.2
  provider: ^6.0.5
  flutter_dotenv: ^5.1.0
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - .env 